apiVersion: v1
kind: Pod
metadata:
   name: mysqlpod1
spec:
   containers:
    - image: mysql
      name: mysqlcontainer
      ports:
        - containerPort: 3306
      env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
            secretKeyRef:
                 name: mysqlpass
                 key: MYSQL_ROOT_PASSWORD
